### ISSUE TITLE
Create Channel > The channel creation time is incorrect

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#311]
# Actual Result
After creating a channel, it always displays the timestamp `1 Jan 1970 08:00`
![image](https://user-images.githubusercontent.com/69950655/109767311-ed335600-7c29-11eb-874d-091b68c7c041.png)

# Expected Result
It should display the correct time when the channel created

# Environment
Both android and iOS app
Build version: 2.2.9

**Comment by bobs4462** [comment]
@tlle14 Hello, we decided not to show any time if the channel has no last_activity, because that's the value we show on channel item. The fix should be available in the next build

**Comment by tlle14** [comment]
Hi @bobs4462 
Some channel still shows the timestamp. 
Do we have any rules for showing the time of a channel?
![processed.jpeg](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/3cd0b6f2-abc4-44ac-8c23-086f3abd85b2)

**Comment by bobs4462** [comment]
Hello @tlle14 What do you mean by time of the channel? Like creation date? Do you suggest that we always show creation date of the channel or that we intermix creation date with last activity timestamp?

**Comment by tlle14** [comment]
Hello @bobs4462 
Sorry for misunderstanding your previous comment. Let me retest

**Comment by tlle14** [comment]
Hi @bobs4462 
I retested and here what I observed:
- Create a new channel:  no timestamp displaying => OK
- Post a message in the new channel: the timestamp displays => OK

https://user-images.githubusercontent.com/69950655/110570163-13a44480-8188-11eb-8383-775c3da6d666.mp4


But there's a channel that has the latest message is 24 Feb, it doesn't display the timestamp. 
Could you please investigate what happens to this channel? (Tell me if you need a login credential)

**Comment by bobs4462** [comment]
@RomaricMourgues can you please check, why are we not always receiving last_activity timestamp on web.qa?

**Comment by tlle14** [comment]
Hi @bobs4462 
I don't see the change or any fix. Why this ticket in the QA-testing column?

**Comment by bobs4462** [comment]
> I'm looking at it, probably a regression on the new release

@RomaricMourgues Hello, did you manage to find the cause of the issue?

**Comment by RomaricMourgues** [comment]
Woops sorry, it was fixed this week, it should be working, tell me if not.

**Comment by bobs4462** [comment]
Romaric, I think it is still broken. For example

```curl --location --request GET 'https://chat.twake.app/internal/services/channels/v1/companies/56393af2-e5fe-11e9-b894-0242ac120004/workspaces/42b997e8-e15b-11ea-bf1d-0242ac120004/channels?mine=true' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU1NjkwNDcsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2MTU1NjQ4NDcsIm5iZiI6MTYxNTU2NDg0Nywic3ViIjoiNTI2OGZhODAtMTlkMi0xMWViLWI3NzQtMDI0MmFjMTIwMDA0IiwiZW1haWwiOiJibWFraG11ZG92QGxpbmFnb3JhLmNvbSIsIm9yZyI6W119.1vCrGda9FKWmuY1585gDzgSPhqEpqlBO6OAmTpJENz0' \
--header 'Cookie: SERVERID177197=1c597a45|YEuTI|YEuSb'```

This request returns all the channels in Home workspace (Linagora
company), if you look up the Covid 19 channel there and check its
last_activity field, it's 0, though there's definitely messages in
there.

If I can provide you with more information, just ask :)


On 21/03/12 05:24AM, Romaric Mourgues wrote:
> Woops sorry, it was fixed this week, it should be working, tell me if not.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Twake/Mobile/issues/311#issuecomment-797487679

**Comment by bobs4462** [comment]
ping @RomaricMourgues, anything on this one? As I said, if you need any extra information, just ask :)

**Comment by RomaricMourgues** [comment]
For Covid19 this is because last message is from November. The last_activity information works only since 1 month ago, and the last_message information only since today :)

**Comment by RomaricMourgues** [comment]
This is what you should receive now on chat.twake.app and on web.qa.twake.app:
<img width="748" alt="Screenshot 2021-03-15 at 16 09 18" src="https://user-images.githubusercontent.com/14353924/111175737-01237400-85a9-11eb-8193-8d64445724ce.png">

**Comment by bobs4462** [comment]
Got it, thanks ;)

**Comment by bobs4462** [comment]
@tlle14 As Romaric said earlier, the last_activity time only apeares for channels and directs which had some activity starting from mid February. For new users this should not be a problem however, as all their data is going to be new.

**Comment by tlle14** [comment]
Thank @bobs4462 and @RomaricMourgues
